### ISSUE TITLE
Clicking icon a second time blanks out the list

### ISSUE THREAD

**Issue by jasonrush** [exaybachay-ak/IPINT#7]
Clicking the extension icon a second time (ie while the list of IP addresses modal is already open) causes the list modal to become empty (the list of IP addresses as well as the close and transparency icons) which makes the extension unusable (and the page potentially) until the page is refreshed.

**Comment by exaybachay-ak** [comment]
Fixed this with most recent merge, "Fix issue #7".  Not 100% ideal, but it addresses the problem.
